config/routes.rb
BearsHeavenRails::Application.routes.draw do
  get "welcome/index"

  resources :games, :only => [:new, :create, :index]

  root :to => 'welcome#index'

end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :difficulty, :magnification, :name, :point
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    render :layout => false
  end

  def create
    score = Score.new(params[:score])
    score.save!
    render json: {status: true}
  end

  def index
    @scores = Score.order("point desc").limit(10)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.haml
%h1 Score

%table
  %th rank
  %th name
  %th score
  %th difficulty
  %th max_magnification
  - @scores.each_with_index do |s, i|
    %tr
      %td= i+1
      %td= s.name
      %td= s.point
      %td= s.difficulty
      %td= s.magnification

app/views/games/new.html.haml
= javascript_include_tag "application"
= stylesheet_link_tag    "application", :media => "all"
= csrf_meta_tags
%meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
= javascript_include_tag "games"
#confirmDialog{title: "Send score", style: "display:none;"}
  Your name
  = text_field_tag 'name', '', {name: "name", id: "name"}

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title BearsHeavenRails
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
  %body
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1= link_to "Bears Heaven", "/"
      %section.top-bar-section
        %ul.left
        %ul.right
    .row
      .small-11.large-offset-1.columns
        = yield

app/views/welcome/index.html.haml
%h2 Welcome
%h3 Contents
%ul
  %li= link_to "play game", new_game_path
  %li= link_to "show score", games_path 
%h3 Tutorial
%h4 how to play
%p=image_tag 'move.png'
%p=image_tag 'jump.png'

%p or use cursor key on keyboard.

%h4 evade

=image_tag 'evade.png'

%h4 attack

=image_tag 'attack.png'

%p score up!

=image_tag 'score.png'

%h4 increase difficulty
%p very easy
%p= image_tag 'veryeasy.png'
%p easy
%p= image_tag 'easy.png'
%p normal
%p= image_tag 'normal.png'
%p hard
%p= image_tag 'hard.png'
%p very hard
%p= image_tag 'veryhard.png'

%h4 enemy
%table
  %tr
    %td
      #bear
    %td= image_tag 'bear.png'
  %tr
    %td
      #polar
    %td= image_tag 'polar.png'
  %tr
    %td
      #space
    %td= image_tag 'space.png'
  %tr
    %td
      #board
    %td= image_tag 'board.png'